### PR TITLE
Feature/itc repoeter

### PR DESCRIPTION
**Pull request by mako-to**
iTunes Connect Reporter Tool for Node.js. This module will be OSS. I'd like a code review. > @smarteducationltd/engineer

### CODE REVIEW

**Comment by mako-to** [comment]
[itc-reporer を NPM として公開する](https://trello.com/c/YOqj21Vg/6-itc-reporer-npm)

**Comment by hiroyukky** [comment]
Awesome!

LGTM

**Comment by mako-to** [comment]
Thank you for the Review.

**Comment by mako-to** [comment]
[iTunes Connect Reporter を使うようにする](https://trello.com/c/ygDQ0yhw/1-itunes-connect-reporter)

**Pull request merged**
